### ISSUE TITLE
Create tests

### ISSUE THREAD

**Issue by Maximaximum** [souldreamer/xhr2-cookies#4]
This project definitely needs thorough tests to make sure it always works as expected.

An obvious way to do it would be to copy the tests from https://github.com/pwnall/node-xhr2, but enhance them with cookie-specific tests (if possible).

**Comment by souldreamer** [comment]
Definitely, I agree. Switching between CoffeeScript and TypeScript was confusing and apparently error-prone. Thanks a lot for your help in finding them.
